// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjihqzlgmwetchallgkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqaWhxemxnbXdldGNoYWxsZ2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDA0NzIsImV4cCI6MjA3Mzc3NjQ3Mn0.oRV7bphUUJhZtioqngTve8ZsFklsNxmqXO7tyUxbSLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});